Repository DigitalProductInnovationAndDevelopment/Anti-Pattern-Analysis, pull requests merged in 2024-08, with the labels that each got.

#46 Code refactorings and unique method key gen
  config.json
  src/main/java/tum/dpid/CallChainAnalyzer.java
  src/main/java/tum/dpid/config/AnalyzerConfig.java
  src/main/java/tum/dpid/file/CallChainUtils.java
  src/main/java/tum/dpid/file/FileUtils.java
  src/main/java/tum/dpid/graph/CallChainVisitor.java
  src/main/java/tum/dpid/graph/CallGraph.java
  src/main/java/tum/dpid/graph/CallGraphVisualizer.java
  src/main/java/tum/dpid/model/CallChainEntity.java
  src/main/java/tum/dpid/model/MethodDeclarationWrapper.java
  src/main/java/tum/dpid/parser/ASTGenerator.java
  src/main/java/tum/dpid/parser/MethodCollector.java
  src/main/java/tum/dpid/parser/MethodExtractor.java
  src/main/java/tum/dpid/parser/MethodNameVisitor.java
  src/main/java/tum/dpid/util/MethodKeyGenerator.java
Labels: enhancement, tool-development, refactoring-refinement

#52 Feat/dynamic analysis improvement
  src/main/java/tum/dpid/CallChainAnalyzer.java
  src/main/java/tum/dpid/file/FileUtils.java
  src/main/java/tum/dpid/model/resources/AnalysisOutput.java
  src/main/java/tum/dpid/services/DynamicAnalyzer.java
Labels: enhancement, tool-development

#55 Fix csv files
  src/main/java/tum/dpid/file/FileUtils.java
Labels: bug

#56 Feat/fehmi plugin development
  plugin/README.md
  plugin/src/main/kotlin/tum/dpid/toolWindow/AntiPatternToolWindowFactory.kt
  plugin/src/main/resources/META-INF/plugin.xml
  plugin/src/main/resources/META-INF/pluginIcon.svg
Labels: documentation

#58 Docs/uml diagram
  docs/img/system-diagram-horizontal-transparent.png
  docs/img/system-diagram-horizontal.png
  docs/img/system-diagram.png
  docs/uml/system-context.puml
Labels: documentation

#61 Test/dynamic analysis
  README.md
  pom.xml
  src/test/java/tum/dpid/services/DynamicAnalyzerTest.java
  src/test/resources/testValidSnapshotData1.csv
Labels: documentation

#76 Docs/sampling manual
  README.md
  docs/img/sampling-steps/capture-snapshot.png
  docs/img/sampling-steps/export-csv.png
  docs/img/sampling-steps/sampling-start.png
  docs/sampling.md
Labels: documentation
